version: "3.8"
services:
  fastapi-nano:
    container_name: "fastapi-nano-docker-poetry"
    image: "fastapi-nano:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    volumes:
        - .:/code
    ports:
      - 5000:8000
